version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns:
          - "MSTest.*"
          - "Microsoft.Testing.*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
